bookings/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
from .models import User
from . import db
from flask_login import login_required, logout_user, login_user, current_user
from flask_bcrypt import generate_password_hash, check_password_hash

authbp = Blueprint('auth', __name__)

# Checks if the current user is Anonymous or logged in
def is_current_user():
    if current_user.name == 'Guest':
        name = 'Guest'
    else:
        name = current_user.name
    return name

@authbp.route('/login', methods=['GET', 'POST'])
def login():
    loginForm = LoginForm()
    if loginForm.validate_on_submit():
        user_name = loginForm.user_name.data
        password = loginForm.password.data
        remember = True if request.form.get('remember') else False
        user = User.query.filter_by(name=user_name).first()
        # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database
        if not user or not check_password_hash(user.password_hash, password):
            flash('Please check your login details and try again.', 'warning')
            # if the user doesn't exist or password is wrong, reload the page
            return redirect(url_for('auth.login'))
        else:
            login_user(user, remember=remember)
            print('Successfully logged in')
            flash('You logged in successfully', 'success')
            return redirect(url_for('main.index'))
    return render_template('user.html', form=loginForm, heading='Login')

@authbp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegisterForm()
    address = []
    if form.validate_on_submit():
        # if this returns a user, then the email already exists in database
        user = User.query.filter_by(emailid=form.email_id.data).first()
        user = User.query.filter_by(name=form.user_name.data).first()
        if user:  # if a user is found, we want to redirect back to signup page so user can try again
            flash(
                'Email address already exists. Login using that email or try using a different email.', 'warning')
            return redirect(url_for('auth.register'))
        address.append(str(form.street_no.data))
        address.append(form.street_name.data)
        address.append(form.state.data)
        address.append(form.postcode.data)
        address_string = ' '.join(str(item) for item in address)
        user = User(name=form.user_name.data, emailid=form.email_id.data, password_hash=generate_password_hash(
            form.password.data, method='sha256'), phone=form.phone.data, address=address_string)
        db.session.add(user)
        db.session.commit()
        flash('Successfully created new user! Please login to continue.', 'success')
        return redirect(url_for('auth.login'))
    return render_template('user.html', form=form, heading='Register')

@authbp.route("/logout")
@login_required
def logout():
    logout_user()
    flash('You have successfully logged out', 'success')
    return redirect(url_for('main.index'))

bookings/views.py
from flask import Blueprint, render_template, request
from .models import Event
from flask_login import login_required, current_user
from . import db

mainbp = Blueprint('main', __name__)

# Checks if the current user is Anonymous or logged in
def is_current_user():
    if current_user.name == 'Guest':
        name = 'Guest'
    else:
        name = current_user.name
    return name


@mainbp.route('/')
def index():
    return render_template('index.html')


@mainbp.route('/my_bookings')
@login_required
def my_bookings():
    return render_template('events/my_events.html', heading='My Bookings', bookings=current_user.created_bookings)


@mainbp.route('/my_events')
@login_required
def my_events():
    return render_template('events/my_events.html', heading='My Events', events=current_user.created_events)

    
@mainbp.route('/search', methods=['GET', 'POST'])
def search():
    # create query object
    query = db.session.query(Event)
    # loop through arguments
    for arg in request.args:
        # check if arg exists and is not empty
        if (arg == 'genre' and request.args['genre'] != ''):
            # update your query with the arg
            query = query.filter(Event.event_genre.like(f"%{request.args['genre']}%"))

        if (arg == 'city' and request.args['city'] != ''):
            query = query.filter(Event.event_city.like(f"%{request.args['city']}%"))

        # get destinations from your query
        events = query.order_by(Event.title.asc()).all()
        if (arg == 'search' and request.args['search'] != ''):
            query = "%" + request.args['search'] + '%'
            events = Event.query.filter(
                Event.description.like(query)).all()
            events += Event.query.filter(Event.title.like(query)).all()
            events += Event.query.filter(Event.event_city.like(query)).all()
            events += Event.query.filter(Event.event_genre.like(query)).all()
            # Filter out duplicates (__eq__ has been set on the model for comparison)
            events = list(set(events))
    # return all events that meet the search criteria on a page
    return render_template('events/view_events.html', heading='Search Results', events=events)

bookings/templates/base.html
<!doctype html>
<html lang='en'>

<head>
    <!-- Required meta tags -->
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- Ticketsmarter CSS -->
    <link rel='stylesheet' href='{{ url_for("static", filename="css/style.css") }}' />
    <!-- Link to Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">
    <!-- Favicon -->
    <link rel='icon' href='{{ url_for("static", filename="images/icon.png") }}' type='image/x-icon' sizes='16x16' />
    <!-- Title -->
    <title>TicketSmarter - Live Music Near You</title>
</head>

<body>
    <!--Navigation bar-->
    <header>
        <nav class='navbar navbar-expand-lg navbar-dark'>
            <div class='container'>
                <a class='navbar-brand' href='/'><img src='{{ url_for("static", filename="images/icon.png") }}' width='30'
                        height='30' class='d-inline-block align-top' alt=''> TicketSmarter</a>
                <button class='navbar-toggler' type='button' data-bs-toggle='collapse'
                    data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent'
                    aria-expanded='false' aria-label='Toggle navigation'>
                    <span class='navbar-toggler-icon'></span>
                </button>
                <div class='collapse navbar-collapse in' id='navbarSupportedContent'>
                    <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button'
                                data-bs-toggle='dropdown' aria-expanded='false'>City</a>
                            <ul class='dropdown-menu dropdown-menu-dark' aria-labelledby='navbarDropdown'>
                                <!--For each city, create an option in the dropdown menu-->
                                {% for city in cities %}
                                <li><a class='dropdown-item'
                                        href='{{ url_for("events.view_events_city", city_name=city.name.lower()) }}'>{{ city.name.title() }}</a>
                                </li>
                                <hr class='dropdown-divider'>
                                {% endfor %}
                                <li><a class='dropdown-item' href='{{ url_for("events.view_all_events") }}'>
                                        Browse All Events</a></li>
                            </ul>
                        </li>
                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button'
                                data-bs-toggle='dropdown' aria-expanded='false'>
                                Genre
                            </a>
                            <ul class='dropdown-menu dropdown-menu-dark' aria-labelledby='navbarDropdown'>
                                <!--For each genre, create an option in the dropdown menu-->
                                {% for genre in genres %}
                                <li><a class='dropdown-item'
                                        href='{{ url_for("events.view_events", genre=genre.name.lower()) }}'>{{ genre.name.title() }}</a>
                                </li>
                                <hr class='dropdown-divider'>
                                {% endfor %}
                                <li>
                                </li>
                                <li><a class='dropdown-item' href='{{ url_for("events.view_all_events") }}'>Browse All
                                        Events</a></li>
                            </ul>
                        </li>
                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button'
                                data-bs-toggle='dropdown' aria-expanded='false'>
                                Artist
                            </a>
                            <ul class='dropdown-menu dropdown-menu-dark' aria-labelledby='navbarDropdown'>
                                <!--For each artist, create and option in the dropdown menu-->
                                {% for artist in artist_list %}
                                <li><a class='dropdown-item'
                                        href='{{ url_for("events.view_events_artist", headliner=artist.headliner) }}'>{{ artist.headliner }}</a>
                                </li>
                                <hr class='dropdown-divider'>
                                {% endfor %}
                                <li>
                                </li>
                                <li><a class='dropdown-item' href='{{ url_for("events.view_all_events") }}'>Browse All
                                        Events</a></li>
                            </ul>
                        </li>
                        <!--Authenticate the user's login details-->
                        <!--If the user is not signed whilst trying to use the services that require an account, send them to the login page-->
                        <li class='nav-item dropdown'>
                            <a class='nav-link dropdown-toggle' href='{{ url_for("auth.login") }}' id='navbarDropdown'
                                role='button' data-bs-toggle='dropdown' aria-expanded='false'>
                                {% if username|lower == 'guest' %}
                                Sign In
                                {% else %}
                                Welcome, {{ username }}
                                {% endif %}
                            </a>
                            <ul class='dropdown-menu dropdown-menu-dark' aria-labelledby='navbarDropdown'>
                                <li><a class='dropdown-item' href='{{ url_for("main.my_bookings") }}'>My Bookings</a></li>
                                <li>
                                    <hr class='dropdown-divider'>
                                </li>
                                <li><a class='dropdown-item' href='{{ url_for("main.my_events") }}'>My Events</a></li>
                                <li>
                                    <hr class='dropdown-divider'>
                                </li>
                                <li><a class='dropdown-item' href='{{ url_for("events.create") }}'>Create New Event</a>
                                </li>
                                <li>
                                    <hr class='dropdown-divider'>
                                </li>
                                {% if username|lower == 'guest' %}
                                <li><a class='dropdown-item' href='{{ url_for("auth.login") }}'>Login</a></li>
                                <li>
                                    <hr class='dropdown-divider'>
                                </li>
                                <li><a class='dropdown-item' href='{{ url_for("auth.register") }}'>Sign Up</a></li>
                                {% else %}
                                <li><a class='dropdown-item' href='{{ url_for("auth.logout") }}'>Logout</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!--End Navigation bar-->
    <main>
        <!--Creates error/warning banners-->
        <!--e.g. "You can only edit your own events!"-->
        <br>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="container">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </main>
    <!--Footer with social media and business information-->
    <footer>
        <div class="container">
            <div id="footer">
                <div class="container footer navbar-fixed-bottom">
                    <div class='row'>
                        <div class='col border-bottom'>
                            <!--Creates line with social media tags-->
                            <p>
                                Connect with us
                                <a target="" title="Facebook">
                                    <img src="{{ url_for('static', filename='images/facebook.svg') }}" alt="Facebook"
                                        height="25" width="25" />
                                </a>
                                <a target="" title="Twitter">
                                    <img src="{{ url_for('static', filename='images/twitter.svg') }}" alt="Twitter"
                                        height="25" width="25" />
                                </a>
                                <a target="" title="Youtube">
                                    <img src="{{ url_for('static', filename='images/youtube.svg') }}" alt="Youtube"
                                        height="25" width="25">
                                </a>
                                <a target="" title="Instagram">
                                    <img src="{{ url_for('static', filename='images/instagram.svg') }}" alt="Instagram"
                                        height="25" width="25" />
                                </a>
                            </p>
                        </div>
                        <!--Creates line with business information-->
                        <div class='row'>
                            <p><a href='mailto:info@ticketsmarter.com.au'>info@ticketsmarter.com.au</a> | <a
                                    href='tel:18008425387'>1800TICKETS</a> | &copy; 2021 TicketSmarter Pty Ltd (ABN 92
                                010 129 110). All rights reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
    </footer>
    <!--Boostrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
</body>

</html>

bookings/templates/fourohfour.html
{% extends "base.html" %}
{% block content %}
<br>
<!--Custom 404 error page-->
<div id='page-container' class='container'>
    <div class="row">
        <br>
        <h1>Oops! We looked everywhere...</h1>
        <h4>Something went wrong and we're really sorry! Please try again and if it still doesn't work, try something
            different.</h4>
    </div>
</div><!-- end container -->
{% endblock %}

bookings/templates/index.html
{% extends 'base.html' %}
{% block content %}
<br>
<div id='page-container' class='container'>
    <!--Carousel section-->
    <div class='row'>
        <h1 class='display-5 fw-bold'>What's on in Brisbane...</h1>
    </div>
    <!--Creates 3 slides for the carousel-->
    <div class='row'>
        <div id='whats-on-carousel' class='carousel slide' data-bs-ride='carousel'>
            <div class='carousel-indicators'>
                <button type='button' data-bs-target='#whats-on-carousel' data-bs-slide-to='0' class='active'
                    aria-current='true' aria-label='Slide 1'></button>
                <button type='button' data-bs-target='#whats-on-carousel' data-bs-slide-to='1'
                    aria-label='Slide 2'></button>
                <button type='button' data-bs-target='#whats-on-carousel' data-bs-slide-to='2'
                    aria-label='Slide 3'></button>
            </div>
            <!--Images used on each carousel slide-->
            <div class='carousel-inner'>
                <div class='carousel-item active'>
                    <a href='#'><img src='{{ url_for("static", filename="images/applefest.jpeg") }}'
                            class='d-block img-fluid w-100' alt='Apple Music Festival'></a>
                </div>
                <div class='carousel-item'>
                    <a href='#'><img src='{{ url_for("static", filename="images/live.jpg") }}'
                            class='d-block img-fluid w-100' alt='Paramore Live in Concert'></a>
                </div>
                <div class='carousel-item'>
                    <a href='#'><img src='{{ url_for("static", filename="images/flume.jpg") }}'
                            class='d-block img-fluid w-100' alt='Flume Australian Tour'></a>
                </div>
            </div>
            <!--Creates the previous and next buttons on the carousel-->
            <button class='carousel-control-prev' type='button' data-bs-target='#whats-on-carousel'
                data-bs-slide='prev'>
                <span class='carousel-control-prev-icon' aria-hidden='true'></span>
                <span class='visually-hidden'>Previous</span>
            </button>
            <button class='carousel-control-next' type='button' data-bs-target='#whats-on-carousel'
                data-bs-slide='next'>
                <span class='carousel-control-next-icon' aria-hidden='true'></span>
                <span class='visually-hidden'>Next</span>
            </button>
        </div>
    </div>
    <!--End carousel Section-->
    <br>
    <!--Search and selection section-->
    <div class='row'>
        <h1 class='display-5 fw-bold'>Search For An Event</h1>
    </div>
    <form action="{{ url_for('main.search') }}" class="row gx-3 gy-2 align-items-center">
        <!--Create genre dropdown-->
        <div class="col-md-4">
            <select name="genre" class="form-select">
                <option value='' selected>Select a genre...</option>
                {% for genre in genres %}
                <option value="{{ genre.name.lower()  }}">{{ genre.name.title() }}</option>
                {% endfor %}
            </select>
        </div>
        <!--Create city dropdown-->
        <div class="col-md-4">
            <select name="city" class="form-select">
                <option value='' selected>Select a city...</option>
                {% for city in cities %}
                <option value="{{ city.name.lower() }}">{{ city.name.title() }}</option>
                {% endfor %}
            </select>
        </div>
        <!--Create search bar-->
        <div class="col-md-3">
            <input name="search" class="form-control mr-sm-2" type="search" placeholder="Search"
                aria-label="Search"></input>
        </div>
        <!--Create submit button-->
        <div class="col-md-1">
            <button type="submit" id='searchbtn' class="btn btn-primary btn-block">Submit</button>
        </div>
    </form>
    <!--End search section-->
    <br>
    <!--Featured section-->
    <div class='row'>
        <h1 class='display-5 fw-bold'>Featured Events</h1>
    </div>
    <!--Create a card for each event-->
    <div class='row'>
        {% for event in current_events %}
        <div class='col-12 col-sm-6 col-md-4 col-lg-3 d-flex align-items-stretch'>
            <div class='card mt-4'>
                <img src="{{ event.image }}" class='card-img-top img-fluid' alt=''>
                <div class='card-body d-flex flex-column'>
                    <h4 class='card-title'><a href='{{ url_for("events.show", id=event.id) }}'>{{ event.title }}</a></h4>
                    {% if event.tickets_remaining == 0 %}
                    <h5 class='card-subtitle mb-2' style="color:red">{{ event.event_status.name.title() }}</h5>
                    <h6 class='card-subtitle mb-2'>{{event.event_genre.name.title()}}</h6>
                    {% else %}
                    <h5 class='card-subtitle mb-2' style="color:green">{{ event.event_status.name.title() }}</h5>
                    <h6 class='card-subtitle mb-2'>{{ event.event_genre.name.title() }}</h6>
                    {% endif %}
                    <p id='index-cards' class='card-text'>{{ event.description }}</p>
                    <a href='{{ url_for("events.show", id=event.id) }}' class='mt-auto btn btn-outline-dark'>See more</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!--End featured section-->
    <br>
    <!--Genre section-->
    <div class='row'>
        <h1 class='display-5 fw-bold'>Browse by Genre</h1>
    </div>
    <!--Create card for each genre-->
    <div class='row'>
        {% for genre in genres %}
        <div class='col-6 col-xl-4'>
            <a id='genre-links' href='{{ url_for("events.view_events", genre=genre.name.lower()) }}'>
                <img id='genre-images' class='img-fluid shadow-lg  bg-white text-white rounded-circle border border-dark m-auto d-block'
                    src="{{ url_for('static', filename='images/{0}.png'.format(genre.name|lower)) }}">
                <div class="d-flex justify-content-center">
                    <p>{{ genre.name.title() }}</p>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
<!--End genre section-->
<br>
<!--City section-->
<div class='row'>
    <h1 class='display-5 fw-bold'>Browse by City</h1>
</div>
<!--Create card for each city-->
<div class='row justify-content-center'>
    {% for city in cities %}
    <div class='col-6 col-xl-4'>
        <a id='genre-links' href='{{ url_for("events.view_events_city", city_name=city.name.lower()) }}'>
            <img id='genre-images' class='img-fluid shadow-lg rounded-circle border border-dark m-auto d-block'
                src='{{ url_for("static", filename="images/{0}.jpg".format(city.name|lower)) }}'>
            <div class="d-flex justify-content-center">
                <p>{{ city.name.title() }}</p>
        </a>
            </div>
    </div>
    {% endfor %}
</div>
<!--End city section-->
<!--End container -->
{% endblock %}

bookings/templates/user.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}
{% block content %}

<!-- Display page-header -->
<div id='page-container' class="container">
    <div class='row'>
        <div class='col-md-6 ml-5'>
            <div class="page-header">
                <br>
                <h1>{{ heading }}</h1>
            </div>
        </div>
    </div>
    <div class="col-md-6 ml-5">
        {{ render_form(form) }}
    </div>
    <!-- When you have login form, then show the user a link to register -->
    {% if heading|lower =='login' %}
    <div class="col-md-4 mb-5 ml-5">
        <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
    </div>
    {% endif %}
</div><!-- end container -->
{% endblock %}